"""empty message

Revision ID: 7d40cc6be97f
Revises: ffdc0a98111c
Create Date: 2022-08-02 20:48:50.010230

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7d40cc6be97f'
down_revision = 'ffdc0a98111c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('street', sa.String(length=200), nullable=False))
    op.add_column('users', sa.Column('city', sa.String(length=50), nullable=False))
    op.add_column('users', sa.Column('state', sa.String(length=50), nullable=False))
    op.add_column('users', sa.Column('zip_code', sa.Integer(), nullable=False))
    op.add_column('users', sa.Column('country', sa.String(length=50), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'country')
    op.drop_column('users', 'zip_code')
    op.drop_column('users', 'state')
    op.drop_column('users', 'city')
    op.drop_column('users', 'street')
    # ### end Alembic commands ###
